export const BOARD_SELECT_CELL = "BOARD_SELECT_CELL";
export const BOARD_GENERATE_NEW = "BOARD_GENERATE_NEW";
export const BOARD_INSERT_NUMBER = "BOARD_INSERT_NUMBER";

export const GAME_GENERATE_NEW = "GAME_GENERATE_NEW";
